### ISSUE TITLE
Need guidance for JATS2LaTeX exception error!

### ISSUE THREAD

**Issue by john15071978** [Vitaliy-1/JATS2LaTeX#1]
Hi Sir,
I have found this repository by googling. I have downloaded this repository and tried but I have received below error:
![screen](https://user-images.githubusercontent.com/5538559/27830170-c8e9040e-60e2-11e7-9787-c7691de84e35.png)

I am using Java version of 8 as below screenshot:
![screen1](https://user-images.githubusercontent.com/5538559/27830218-0945ffa2-60e3-11e7-9631-a12786aca5c9.png)

Also I have successfully installed MiKTeX 2,9.
![screen2](https://user-images.githubusercontent.com/5538559/27830381-cd8108f8-60e3-11e7-99e5-b2c88b370074.png)
Please guide me what I am missing. Your response is very helpful to me.

**Comment by Vitaliy-1** [comment]
Probably you are using master branch. It requires 4 arguments. There is a need to point 1 more tex file, it will have our Ukrainian GOST standard. Try to download and execute jar file from a release, I have created it for public use: https://github.com/Vitaliy-1/JATS2LaTeX/releases

**Comment by john15071978** [comment]
Hi Sir,
Thanks for your kind reply. Now it works fine.

**Comment by Vitaliy-1** [comment]
Master branch now accepts 3 arguments.
