### ISSUE TITLE
Problems with subsections

### ISSUE THREAD

**Issue by mittinatten** [Vitaliy-1/JATS2LaTeX#2]
Hi,
Thank you for this excellent library! I think I have found a bug. In the example article only one of the sections has subsections and works as expected, but if you have several sections with subsections, each section gets all subsections. Example: 
~~~~xml
<sec>
  <title>A</title>
  <sec><title>a</title></sec>
</sec>
<sec>
  <title>B</title>
  <sec><title>b</title></sec>
</sec>
~~~~
becomes
~~~~tex
\section{A}
\subsection{a}
\subsection{b}
\section{B}
\subsection{a}
\subsection{b}
~~~~
should be
~~~~tex
\section{A}
\subsection{a}
\section{B}
\subsection{a}
~~~~

Simon

**Comment by Vitaliy-1** [comment]
Thanks,
But I wish I knew programming better when was writing this parser :)

This commit probably fixes this issue. Will take a closer look later: 
https://github.com/Vitaliy-1/JATS2LaTeX/commit/d8dbabab0836688ff274cc86a71584dc8ed260ce

**Comment by Vitaliy-1** [comment]
Hi @mittinatten 
Now in the master branch and in the new release.

**Comment by mittinatten** [comment]
Perfect! Thanks
